config/routes.rb
NSCD::Application.routes.draw do
  devise_for :users, controllers: {
		sessions: "users/sessions",
		registrations: "users/registrations",
		passwords: "users/passwords"
	}

  root 'issues#index'

	resources :issues do
		member do
			get 'close'
			get 'open'
		end
		scope :module => :issues do
			resources :comments
		end
	end

	resources :settings do
		collection do
			get   'profile'
			patch 'profile', :action => 'profile_update'
		end
	end

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :creator, class_name: 'User'
	has_many :label_ships
  has_many :labels, :through => :label_ships
  has_many :comments
	enum status: [ :is_open, :is_close ]

	before_save :default_values
	def default_values
		self.status ||= self.class.statuses[:is_open]
	end
end

app/models/issue/comment.rb
class Issue::Comment < ActiveRecord::Base
  belongs_to :issue
  belongs_to :author, class_name: 'User',
                      foreign_key: 'author_id'
	enum status: [ :is_comment, :is_close, :is_open ]

	before_save :default_values
	def default_values
		self.content ||= ""
		self.status ||= self.class.statuses[:is_comment]
	end
end

app/models/issue/label.rb
class Issue::Label < ActiveRecord::Base
	has_many :label_ships
	has_many :issues, :through => :label_ships
end

app/models/issue/label_ship.rb
class Issue::LabelShip < ActiveRecord::Base
	belongs_to :issue
	belongs_to :label
end

app/controllers/issues/comments_controller.rb
class Issues::CommentsController < ApplicationController
  authorize_resource :class => 'Issue::Comment', :through => :issue

	def create
		issue = Issue.find params[:issue_id]
		issue.comments << @comment = Issue::Comment.create do |c|
			c.author = current_user
			c.content = post_params[:content]
		end
		redirect_to issue
	end

	def post_params
		params.require(:issue_comment).permit(:content)
	end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
	authorize_resource
  def index
		@status = params[:status] == 'closed' ? 'closed' : 'opened'
		status = @status == 'closed' ? :is_close : :is_open
		@sort = params[:sort] || 'newest'
		@sort = 'newest' unless %W(newest oldest newest_update oldest_update).include? @sort
		sort = case @sort.to_s.to_sym
						when :newest
							{:created_at => :desc}
						when :oldest
							{:created_at => :asc}
						when :newest_update
							{:updated_at => :desc}
						when :oldest_update
							{:updated_at => :asc}
						#when :most_comments
						#	{:comments_count => :desc}
						#when :least_comments
						#	{:comments_count => :desc}
						else
							{:created_at => :desc}
						end
		@labels = Issue::Label.all
		@issues = Issue.where(status: Issue.statuses[status]).order(sort).page params[:page]
  end

	def show
		@issue = Issue.find params[:id]
	end

	def new
		@issue = Issue.new do |i|
			i.creator = current_user
		end
	end

	def create
		issue = Issue.create do |i|
			i.creator = current_user
			i.title = post_params[:title]
		end
		issue.comments << Issue::Comment.create do |c|
			c.author = current_user
			c.content = post_params[:comment][:content]
		end
		issue.labels << post_params[:labels].map do |id|
			Issue::Label.find id unless id.empty?
		end - [nil]
		redirect_to issue
	end

	def close
		@issue = Issue.find params[:id]
		if @issue.is_open?
			@issue.is_close!
			@issue.comments << Issue::Comment.create do |c|
				c.author = current_user
				c.is_close!
			end
		end
		redirect_to @issue
	end

	def open
		@issue = Issue.find params[:id]
		if @issue.is_close?
			@issue.is_open!
			@issue.comments << Issue::Comment.create do |c|
				c.author = current_user
				c.is_open!
			end
		end
		redirect_to @issue
	end

	def post_params
		params.require(:issue).permit(:title, :comment => [:content], :labels => [])
	end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_comment.html.slim
div.comment.ui.form
  a.avatar
    img src='http://placehold.it/32'
  div.content
    = form_for Issue::Comment.new, url: issue_comments_path(@issue) do |f|
      a.author
        = current_user.displayname
      div.text
        = f.text_area :content, placeholder: '回應……'
      = f.submit '送出', class: 'ui floated right small blue submit button'

app/views/issues/index.html.slim
div.ui.grid
  div.four.wide.column
    div.ui.vertical.segment
      h5.ui.header
        | 標籤
      div.ui.animated.selection.list
        - @labels.each do |label|
          a.item
            div.ui.large.circular.label class="#{label.color || 'black'}"
            | &nbsp;
            = label.name
  div.twelve.wide.column
    div
      div.ui.small.buttons
        = link_to issues_path(sort: @sort), class: 'ui button' << actived?(@status == 'opened') do
          = semantic_icon :exclamation
          | 待處理
        = link_to issues_path(status: 'closed', sort: @sort), class: 'ui button' << actived?(@status == 'closed') do
          = semantic_icon :checkmark
          | 已結案
      | &nbsp;
      div.ui.small.buttons
        div.ui.dropdown.right.attached.labeled.icon.button
          = semantic_icon :sort
          | 排序：
          = '最新' if @sort == 'newest'
          = '最舊' if @sort == 'oldest'
          = '最近動態' if @sort == 'newest_update'
          = '最早動態' if @sort == 'oldest_update'
          div.menu
            = link_to issues_path(status: @status), class: 'item'
              = semantic_icon :sort, :attributes, :descending
              | 最新
            = link_to issues_path(sort: 'oldest', status: @status), class: 'item'
              = semantic_icon :sort, :attributes, :ascending
              | 最舊
            = link_to issues_path(sort: 'newest_update', status: @status), class: 'item'
              = semantic_icon :sort, :attributes, :descending
              | 最近動態
            = link_to issues_path(sort: 'oldest_update', status: @status), class: 'item'
              = semantic_icon :sort, :attributes, :ascending
              | 最早動態
      - if can? :create, Issue
        div.ui.floated.right.small.buttons
          = link_to new_issue_path, class: 'ui green button' do
            = semantic_icon :add
            | 新增待辦
    div.ui.basic.vertical.segment
      div.ui.relaxed.selection.animated.celled.list
        - @issues.each do |issue|
          = link_to issue, class: 'item' do
            img.ui.avatar.image src='http://placehold.it/32'
            div.content
              div.header.ui.blue
                = issue.title
                - issue.labels.each do |label|
                  | &nbsp;
                  span.ui.small.label class="#{label.color || 'black'}"
                    = label.name
              div.ui.right.corner.label
                div.text
                  | ##{issue.id}
              div.description.ui.font.small
                = issue.creator.displayname
                |  建立於 #{timeago_tag issue.created_at, :format => :short}
    = paginate @issues

app/views/issues/new.html.slim
= form_for @issue do |f|
  div.ui.grid
    div.sixteen.wide.column
      div.ui.form.raised.segment
        div.ui.tiny.header
          / div.ui.red.ribbon.label
          /   | 待處理
          div.ui.input
            = f.text_field :title, placeholder: '標題'
            div.ui.corner.label
              = semantic_icon :asterisk
        img.ui.tiny.avatar.image src='http://placehold.it/32'
        = @issue.creator.displayname
        |  建立於 現在
    div.twelve.wide.column
      div.ui.form.comments
        div.comment
          a.avatar
            img src='http://placehold.it/32'
          div.content
            a.author
              = @issue.creator.displayname
            div.text
              = f.fields_for :comment do |comment|
                = comment.text_area :content, placeholder: '詳細說明……'
    div.four.wide.column
      div.ui.vertical.segment
        h5.ui.header
          | 標籤
        div.ui.list
          / = f.fields_for :labels do |l|
          = f.collection_check_boxes :labels, Issue::Label.all, :id, :name do |b|
            div.item
              div.ui.checkbox
                = b.check_box
                = b.label
                  span.ui.small.label class="#{b.object.color || 'black'}"
                    = b.text
    div.sixteen.wide.column
      div.ui.divider
      div.ui.form
        = f.submit '送出', class: 'ui floated right blue submit button'

app/views/issues/show.html.slim
div.ui.grid
  div.sixteen.wide.column
    div.ui.raised.segment
      h2.ui.header
        div.ui.right.corner.label
          div.text
            | ##{@issue.id}
        - if @issue.is_open?
          div.ui.red.ribbon.label
            | 待處理
        - else
          div.ui.blue.ribbon.label
            | 已結案
        = @issue.title
      img.ui.tiny.avatar.image src='http://placehold.it/32'
      = @issue.creator.displayname
      |  建立於 #{timeago_tag @issue.created_at, :format => :short}
  div.twelve.wide.column
    div.ui.comments
      - @issue.comments.each do |comment|
        - if comment.is_comment?
          div.comment
            a.avatar
              img src='http://placehold.it/32'
            div.content
              a.author
                = comment.author.displayname
              div.metadata
                = timeago_tag comment.created_at, :format => :short
              div.text
                div.ui.segment
                  = comment.content
        - elsif comment.is_open?
          div.ui.tiny.inverted.red.block.header
            img.ui.tiny.avatar.image src='http://placehold.it/32'
            a.author
              = comment.author.displayname
            |  於#{timeago_tag comment.created_at, :format => :short}翻案
        - else
          div.ui.tiny.inverted.green.block.header
            img.ui.tiny.avatar.image src='http://placehold.it/32'
            a.author
              = comment.author.displayname
            |  於#{timeago_tag comment.created_at, :format => :short}結案
      - if can? :create, Issue::Comment
        = render :partial => 'comment'
  div.four.wide.column
    div.ui.vertical.segment
      h5.ui.header
        | 標籤
      div.ui.labels
        - @issue.labels.each do |label|
          a.ui.label class="#{label.color || 'black'}"
            = label.name
  - if can? :modify, Issue
    div.sixteen.wide.column
      div.ui.divider
      div.ui.form
        - if @issue.is_open?
          = link_to close_issue_path(@issue), class: 'ui floated right green submit button'
            | 結案
        - else
          = link_to open_issue_path(@issue), class: 'ui floated right red submit button'
            | 翻案