config/routes.rb
NSCD::Application.routes.draw do
  devise_for :users, controllers: {
		sessions: "users/sessions",
		registrations: "users/registrations",
		passwords: "users/passwords"
	}

  root 'issues#index'

	resources :issues do
		member do
			get 'close'
			get 'open'
		end
		scope :module => :issues do
			resources :comments
		end
	end

	resources :settings do
		collection do
			get   'profile'
			patch 'profile', :action => 'profile_update'
		end
	end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	authorize_resource User
	skip_authorization_check :only => :index
	before_filter :load_user, :except => :index

	def index
		redirect_to :action => :profile
	end
	
	def profile
	end

	def profile_update
		@user.firstname = profile_params[:firstname]
		@user.lastname = profile_params[:lastname]
		@user.nickname = profile_params[:nickname]
		@user.phone = profile_params[:phone]
		@user.save
		flash[:success] = "更新成功"
		redirect_to :action => :profile
	end

	def account
	end

	private

	def load_user
		@user = User.find current_user
	end

	def profile_params
		params.require(:user).permit(:lastname, :firstname, :nickname, :phone)
	end
end

app/views/settings/_menu.html.slim
div.ui.secondary.vertical.pointing.menu
  = link_to profile_settings_path, class: 'item' << actived?(params[:action] == 'profile')
    = semantic_icon :user
    | 個人檔案
  a.item
    = semantic_icon :setting
    | 帳號設定

app/views/settings/profile.html.slim
div.ui.grid
  - if flash[:success]
    div.sixteen.wide.column
      div.ui.success.message
        div.header
          = flash[:success]
  div.four.wide.column
    = render :partial => 'menu'
  div.twelve.wide.column
    div.ui.basic.segment
      = form_for @user, url: profile_settings_path do |f|
        div.ui.form
          div.field
            label
              | 使用者頭像
            = image_tag '//placehold.it/48'
          div.field
            = f.label :username
              | 帳號
            div.ui.left.labeled.icon.input
              = semantic_icon :user
              = f.text_field :username, readonly: 'readonly'
              div.ui.corner.label
                = semantic_icon :lock
          div.ui.two.fields
            div.field
              = f.label :lastname
                | 姓
              div.ui.left.labeled.icon.input
                = semantic_icon :half, :empty, :star
                = f.text_field :lastname
            div.field
              = f.label :firstname
                | 名
              div.ui.left.labeled.icon.input
                = semantic_icon :horizontally, :flipped, :half, :empty, :star
                = f.text_field :firstname
          div.field
            = f.label :nickname
              | 暱稱
            div.ui.left.labeled.icon.input
              = semantic_icon :user
              = f.text_field :nickname
          div.field
            = f.label :phone
              | 電話號碼
            div.ui.left.labeled.icon.input
              = semantic_icon :phone
              = f.text_field :phone
          = f.submit '確定修改', class: 'ui blue submit button'